"""Live debate mode — real Claude agents over the Anthropic API.

Cost-tiered per the spec: Opus for the Director's synthesis judgment,
Sonnet for specialist workstreams, Haiku for structured parsing.
The orchestration protocol, audit gate, conviction math, rating build and
publish path are inherited from the simulation engine — only the judgment
text is generated by models. Engines still make every calculation.
"""
from __future__ import annotations

import asyncio
import json
import os
from typing import Any, Literal

import anthropic
from pydantic import BaseModel, Field

from . import analysis, conviction
from .sim import SimDebate, _pace
from .state import (
    AgentId, AgentView, Claim, KeyNumber, Objection, Phase, Rebuttal,
    Thesis, ThesisPillar, Verdict,
)

DIRECTOR_MODEL = os.environ.get("DELPHI_MODEL_DIRECTOR", "claude-opus-4-8")
SPECIALIST_MODEL = os.environ.get("DELPHI_MODEL_SPECIALIST", "claude-sonnet-4-6")
PARSER_MODEL = os.environ.get("DELPHI_MODEL_PARSER", "claude-haiku-4-5")


# ---------- structured extraction schemas ----------

class ParsedClaim(BaseModel):
    text: str = Field(description="One factual, numeric claim from the analysis")
    citation_keys: list[str] = Field(description="Citation registry keys backing the claim")
    confidence: float = Field(ge=0, le=1)


class ParsedKeyNumber(BaseModel):
    label: str
    value: str
    delta: str | None = None
    tone: Literal["pos", "neg", "neutral"]


class ParsedView(BaseModel):
    stance: float = Field(ge=-2, le=2, description="-2 bearish .. +2 bullish")
    summary: str = Field(description="One-line desk summary, max 18 words")
    claims: list[ParsedClaim] = Field(min_length=2, max_length=4)
    key_numbers: list[ParsedKeyNumber] = Field(min_length=2, max_length=3)


class ParsedObjection(BaseModel):
    target_agent: Literal["fundamentals", "valuation", "sentiment", "macro"]
    text: str
    weight: float = Field(ge=3, le=15, description="Conviction points at stake")


class ParsedObjections(BaseModel):
    objections: list[ParsedObjection] = Field(min_length=2, max_length=3)


class ParsedVerdict(BaseModel):
    status: Literal["refuted", "mitigated", "standing"]
    rationale: str = Field(description="One sentence")


class ParsedSynthesis(BaseModel):
    headline: str
    pillar_titles: list[str] = Field(min_length=3, max_length=3)
    pillar_texts: list[str] = Field(min_length=3, max_length=3)
    variant_perception: str


SPECIALIST_BRIEFS = {
    AgentId.FUNDAMENTALS: (
        "You are the Fundamentals Analyst on an institutional equity research desk. "
        "Assess growth durability, the margin bridge, cash generation and balance-sheet "
        "quality. Anchor every figure to the fact digest."),
    AgentId.VALUATION: (
        "You are the Valuation Analyst. The deterministic engine has already run the DCF, "
        "comps and Monte Carlo — your job is judgment about the assumptions, not arithmetic. "
        "Use your tools to rerun scenarios when useful. State fair value vs the tape plainly."),
    AgentId.SENTIMENT: (
        "You are the Sentiment & Management Tone Analyst. Read positioning: social skew, "
        "short interest, options, the insider tape. Separate crowding risk from genuine signal."),
    AgentId.MACRO: (
        "You are the Macro & Industry Analyst. Rates, cycle, and especially geographic "
        "exposure — where in the world this P&L is actually earned and what can reach it."),
}


def _digest(bundle: dict[str, Any], valuation: dict[str, Any]) -> str:
    """Compact fact pack injected into every prompt. Models narrate, never invent."""
    slim = {
        "company": bundle["company"], "ticker": bundle["ticker"], "sector": bundle["sector"],
        "as_of": bundle.get("as_of"), "market": bundle["market"] | {"price_history": "omitted"},
        "financials": bundle["financials"], "estimates": bundle["estimates"],
        "ownership": bundle["ownership"], "geo_revenue": bundle["geo_revenue"],
        "social": bundle["social"], "macro": bundle["macro"], "peers": bundle["peers"],
        "engine": {
            "assumptions": valuation["assumptions"],
            "dcf": valuation["dcf"], "dcf_bear": valuation["dcf_bear"], "dcf_bull": valuation["dcf_bull"],
            "comps_pe": valuation["comps_pe"], "comps_ev_ebitda": valuation["comps_ev_ebitda"],
            "monte_carlo_stats": valuation["monte_carlo"]["draws_stats"],
            "prob_upside": valuation["monte_carlo"].get("prob_upside"),
            "ratios": valuation["ratios"], "analyst_targets": valuation["analyst_targets"],
            "last_price": valuation["last_price"],
        },
    }
    return json.dumps(slim, default=str)


class LiveDebate(SimDebate):
    """Same protocol, real judgment. Overrides the narrative phases only."""

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.client = anthropic.AsyncAnthropic()
        self.digest = _digest(self.b, self.v)
        self.s.mode = "live"

    # ---------- shared LLM plumbing ----------

    def _registry_doc(self) -> str:
        return "\n".join(f"- {key}: {cit.source}" for key, cit in self.c.items())

    async def _stream_agent(self, agent: AgentId, system: str, user: str,
                            tools: list[dict] | None = None,
                            model: str = SPECIALIST_MODEL,
                            kind: str = "finding") -> str:
        """Stream one agent turn to the bus, handling tool calls. Returns final text."""
        messages: list[dict[str, Any]] = [{"role": "user", "content": user}]
        full_text: list[str] = []

        for _ in range(6):  # tool-loop ceiling
            mid = self._mid(agent)
            started = False
            async with self.client.messages.stream(
                model=model, max_tokens=1200, system=system,
                tools=tools or [], messages=messages,
            ) as stream:
                async for event in stream:
                    if event.type == "content_block_delta" and event.delta.type == "text_delta":
                        if not started:
                            self.e.message_start(agent, mid, kind)
                            started = True
                        self.e.message_delta(mid, event.delta.text)
                        full_text.append(event.delta.text)
                final = await stream.get_final_message()
            if started:
                self.e.message_end(mid)

            if final.stop_reason != "tool_use":
                break
            messages.append({"role": "assistant", "content": final.content})
            results = []
            for block in final.content:
                if block.type == "tool_use":
                    call_id = self._mid(agent)
                    self.e.tool_call(agent, call_id, block.name, json.dumps(block.input))
                    out = self._exec_tool(block.name, block.input)
                    self.e.tool_result(call_id, out[:300])
                    results.append({"type": "tool_result", "tool_use_id": block.id, "content": out})
            messages.append({"role": "user", "content": results})

        return "".join(full_text)

    def _exec_tool(self, name: str, args: dict[str, Any]) -> str:
        from ..engine import dcf as dcf_engine
        a = self.v["assumptions"]
        try:
            if name == "run_dcf":
                scaled = {
                    **a,
                    "growth_path": [g * args.get("growth_scale", 1.0) for g in a["growth_path"]],
                    "ebit_margin_path": [m + args.get("margin_delta_bps", 0) / 10000
                                         for m in a["ebit_margin_path"]],
                    "terminal_growth": args.get("terminal_growth", a["terminal_growth"]),
                }
                r = dcf_engine.dcf_from_assumptions(scaled)
                return (f"per_share={self.sym}{r['per_share']:.2f}, ev={self.sym}{r['ev']:.0f}B, "
                        f"wacc={r['wacc']:.2%}, tv_share={r['tv_share_of_ev']:.0%}")
            if name == "geo_shock":
                share = next((g["revenue_share"] for g in self.b["geo_revenue"]
                              if g["name"].lower() == str(args.get("region", "")).lower()),
                             max(g["revenue_share"] for g in self.b["geo_revenue"]))
                hit = share * float(args.get("revenue_haircut", 0.4))
                return f"year-one revenue impact ≈ -{hit:.0%} before mitigation"
            return f"unknown tool {name}"
        except Exception as exc:  # tool errors go back to the model, not the user
            return f"tool error: {exc}"

    async def _parse(self, schema: type[BaseModel], prompt: str) -> BaseModel:
        resp = await self.client.messages.parse(
            model=PARSER_MODEL, max_tokens=1500,
            messages=[{"role": "user", "content": prompt}],
            output_format=schema,
        )
        return resp.parsed_output

    def _resolve_cites(self, keys: list[str]) -> list[str]:
        return [self.c[k].id for k in keys if k in self.c]

    # ---------- overridden phases ----------

    async def _plan(self) -> None:
        e = self.e
        e.phase_changed(Phase.PLAN, "Director scopes the engagement")
        e.agent_status(AgentId.DIRECTOR, "thinking")
        await self._stream_agent(
            AgentId.DIRECTOR,
            system=("You are the Research Director of DELPHI, a multi-agent equity research desk. "
                    "Brief, commanding, specific. 3-4 sentences: scope the engagement for this ticker, "
                    "name the four workstreams, and note that the Adversary and a compliance audit gate "
                    "publication."),
            user=f"Open coverage on {self.b['company']} ({self.s.ticker}). Fact digest: {self.digest[:3000]}",
            model=DIRECTOR_MODEL, kind="direction")
        plan = [
            f"Index the {self.s.ticker} document set (10-K, 10-Q, 8-K, DEF 14A)",
            "Fundamentals: growth durability, margin bridge, quality scores",
            "Valuation: DCF + comps + scenario surface (engine-computed)",
            "Sentiment: positioning, insider tape, social skew",
            "Macro: rates, cycle, geographic exposure map",
            "Adversarial review — max 2 objection rounds",
            "Synthesis → conviction → audit → publish",
        ]
        self.s.plan = plan
        e.plan_ready(plan)
        e.agent_status(AgentId.DIRECTOR, "idle")

    async def _parallel_research(self) -> None:
        self.e.phase_changed(Phase.PARALLEL_RESEARCH, "Four specialists fan out")
        for a in SPECIALIST_BRIEFS:
            self.s.views[a.value] = AgentView(agent=a)
        await asyncio.gather(*(self._specialist(a) for a in SPECIALIST_BRIEFS))
        # Valuation artifacts always ship, regardless of what the model said.
        cells, axes = analysis.sensitivity_cells(self.v)
        self.e.valuation_update(
            football_field=analysis.football_field(self.v),
            sensitivity=cells, sensitivity_axes=axes,
            monte_carlo=analysis.monte_carlo_summary(self.v))
        self.e.geo_exposure(analysis.geo_exposure(self.b))

    def _specialist_tools(self, agent: AgentId) -> list[dict]:
        if agent == AgentId.VALUATION:
            return [{
                "name": "run_dcf",
                "description": "Rerun the deterministic DCF with scaled assumptions. Call this to test bear/bull scenarios instead of guessing numbers.",
                "input_schema": {"type": "object", "properties": {
                    "growth_scale": {"type": "number", "description": "Multiplier on the growth path, e.g. 0.6 for bear"},
                    "margin_delta_bps": {"type": "number", "description": "Additive margin change in basis points"},
                    "terminal_growth": {"type": "number"}}, "required": []},
            }]
        if agent == AgentId.MACRO:
            return [{
                "name": "geo_shock",
                "description": "Quantify the year-one revenue impact of a disruption to one disclosed region. Call when sizing geographic risk.",
                "input_schema": {"type": "object", "properties": {
                    "region": {"type": "string"},
                    "revenue_haircut": {"type": "number", "description": "0..1 fraction of region revenue lost"}},
                    "required": ["region"]},
            }]
        return []

    async def _specialist(self, agent: AgentId) -> None:
        e = self.e
        e.agent_status(agent, "thinking")
        text = await self._stream_agent(
            agent,
            system=(SPECIALIST_BRIEFS[agent] +
                    " Write 4-6 sentences in confident desk voice. Every number must come from the "
                    "fact digest or a tool result — never invent figures. No headers, no bullets."),
            user=f"Fact digest for {self.b['company']} ({self.s.ticker}):\n{self.digest}",
            tools=self._specialist_tools(agent), kind="finding")

        parsed: ParsedView = await self._parse(ParsedView, (
            f"Extract the analyst view from this research finding.\n\nFINDING:\n{text}\n\n"
            f"CITATION REGISTRY (use these keys):\n{self._registry_doc()}\n\n"
            "Pick 2-4 numeric claims verbatim-faithful to the finding, each with the registry keys "
            "that genuinely back it (filings/xbrl for financials, engine for model outputs, "
            "social/form4 for positioning, fred for macro, segments for geography)."))

        view = self.s.views[agent.value]
        view.stance = parsed.stance
        view.summary = parsed.summary
        for pc in parsed.claims:
            self._claim(agent, pc.text, self._resolve_cites(pc.citation_keys), pc.confidence)
        view.key_numbers = [KeyNumber(**kn.model_dump()) for kn in parsed.key_numbers]
        e.key_numbers(agent, view.key_numbers)
        e.view_ready(agent, view.stance, view.summary)
        e.agent_status(agent, "done")

    async def _adversary_round(self, rnd: int) -> None:
        e = self.e
        phase = Phase.ADVERSARY_ROUND_1 if rnd == 1 else Phase.ADVERSARY_ROUND_2
        e.phase_changed(phase, "Objections filed" if rnd == 1 else "Standing objections pressed")
        e.agent_status(AgentId.ADVERSARY, "thinking")

        views_doc = "\n\n".join(
            f"[{v.agent.value}] stance={v.stance:+.1f} — {v.summary}\n" +
            "\n".join(f"  claim {c.id}: {c.text}" for c in v.claims)
            for v in self.s.views.values())

        if rnd == 1:
            text = await self._stream_agent(
                AgentId.ADVERSARY,
                system=("You are the Adversary — the institutional bear-case agent. Your job is to find "
                        "what breaks the thesis, not to be reflexively negative. File exactly 3 sharp, "
                        "specific objections against the weakest claims. Reference actual numbers. "
                        "Direct prose, numbered 1-3."),
                user=f"Specialist findings:\n{views_doc}\n\nEngine facts: {self.digest[:2500]}",
                model=DIRECTOR_MODEL, kind="objection")
            parsed: ParsedObjections = await self._parse(ParsedObjections, (
                f"Extract the objections from this adversarial review:\n{text}\n\n"
                "For each: target_agent (which specialist it attacks), the objection text "
                "(complete, self-contained), and weight 3-15 = conviction points at stake."))
            for i, po in enumerate(parsed.objections, 1):
                o = Objection(id=f"O{i}", round=1, target_agent=AgentId(po.target_agent),
                              target_claim_id=self._claim_for(AgentId(po.target_agent)),
                              text=po.text, weight=round(po.weight, 1))
                self.s.objections.append(o)
                e.objection_filed(o)
                await asyncio.sleep(_pace(0.3))
        else:
            standing = [vd for vd in self.s.verdicts if vd.status == "standing"]
            summary = ("No objections survived rebuttal."
                       if not standing else
                       f"{len(standing)} objection(s) still standing: " + "; ".join(
                           next(o.text for o in self.s.objections if o.id == vd.objection_id)[:120]
                           for vd in standing))
            await self._stream_agent(
                AgentId.ADVERSARY,
                system=("You are the Adversary closing round two. 2-3 sentences. If objections stand, "
                        "press the strongest one and state it stays on the risk register at full weight. "
                        "If none stand, concede cleanly — evidence won."),
                user=summary, model=DIRECTOR_MODEL, kind="objection")
        e.agent_status(AgentId.ADVERSARY, "done")

    async def _rebuttals(self) -> None:
        e = self.e
        e.phase_changed(Phase.REBUTTAL, "Specialists respond with evidence")
        for i, o in enumerate(self.s.objections, 1):
            agent = o.target_agent
            e.agent_status(agent, "rebutting")
            text = await self._stream_agent(
                agent,
                system=(SPECIALIST_BRIEFS[agent] +
                        " The Adversary has objected to your work. Rebut in 2-4 sentences with evidence — "
                        "rerun a tool if it strengthens the answer. Concede what is true; quantify what "
                        "can be bounded. Never bluster."),
                user=f"OBJECTION: {o.text}\n\nYour fact digest: {self.digest[:2500]}",
                tools=self._specialist_tools(agent), kind="rebuttal")
            r = Rebuttal(id=f"R{i}", objection_id=o.id, agent=agent, text=text,
                         citation_ids=self._cite("engine"))
            self.s.rebuttals.append(r)
            e.rebuttal_filed(r)

            pv: ParsedVerdict = await self._parse(ParsedVerdict, (
                f"You are a neutral debate judge.\nOBJECTION: {o.text}\nREBUTTAL: {text}\n\n"
                "Verdict: 'refuted' if the rebuttal directly disproves the premise with evidence; "
                "'mitigated' if it bounds/quantifies the risk credibly; 'standing' if the core "
                "exposure remains. One-sentence rationale."))
            vd = Verdict(objection_id=o.id, status=pv.status, rationale=pv.rationale,
                         penalty_applied=o.weight if pv.status == "standing"
                         else (o.weight * 0.35 if pv.status == "mitigated" else 0.0))
            self.s.verdicts.append(vd)
            e.verdict_rendered(vd)
            e.agent_status(agent, "done")

    async def _synthesis(self) -> None:
        e, s = self.e, self.s
        e.phase_changed(Phase.SYNTHESIS, "Director assembles thesis + conviction")
        e.agent_status(AgentId.DIRECTOR, "thinking")

        rating = self._build_rating()
        s.rating = rating
        views = list(s.views.values())
        uncited = sum(1 for vw in views for c in vw.claims if not c.citation_ids)
        conv = conviction.score(views, s.objections, s.verdicts, uncited)
        s.conviction = conv

        street_mean = self.v["analyst_targets"]["mean"]
        street_doc = f"{self.sym}{street_mean:.0f}" if street_mean is not None else "unavailable (no coverage)"
        debate_doc = "\n".join(
            f"O: {o.text[:160]} → {next((vd.status for vd in s.verdicts if vd.objection_id == o.id), '?')}"
            for o in s.objections)
        text = await self._stream_agent(
            AgentId.DIRECTOR,
            system=("You are the Research Director synthesizing the debate into a thesis. 4-6 sentences: "
                    "the call, why the engine's target differs from the street (the variant perception), "
                    "and how the surviving objections are priced. Reference the conviction breakdown "
                    "explicitly — the number is a formula, not a feeling."),
            user=(f"Rating: {rating.action}, target {self.sym}{rating.price_target:.2f} vs {self.sym}{rating.last_price:.2f} "
                  f"({rating.upside_pct:+.1%}). Conviction {conv.final:.0f} = base {conv.base_agreement:.0f} "
                  f"− objections {conv.objection_penalty:.0f} − citations {conv.citation_penalty:.0f}.\n"
                  f"Street mean target: {street_doc}.\n"
                  f"Debate outcomes:\n{debate_doc}\n\nSpecialist stances: "
                  + ", ".join(f"{v.agent.value} {v.stance:+.1f}" for v in views)),
            model=DIRECTOR_MODEL, kind="direction")

        parsed: ParsedSynthesis = await self._parse(ParsedSynthesis, (
            f"Extract the thesis from this synthesis:\n{text}\n\n"
            "headline: one line with rating + target. 3 pillar titles + 3 pillar texts "
            "(short, specific). variant_perception: where and why this view differs from consensus."))
        pillars = [ThesisPillar(title=t, text=x, citation_ids=self._cite("engine", "xbrl"))
                   for t, x in zip(parsed.pillar_titles, parsed.pillar_texts)]
        thesis = Thesis(headline=parsed.headline, pillars=pillars,
                        variant_perception=parsed.variant_perception)
        s.thesis = thesis
        e.thesis_ready(thesis)
        e.rating_ready(rating)
        e.conviction_update(conv)
        e.agent_status(AgentId.DIRECTOR, "done")

    async def _revise(self) -> None:
        e, s = self.e, self.s
        e.phase_changed(Phase.REVISE, "Audit failure loops back — once")
        removed = 0
        for view in s.views.values():
            kept = [c for c in view.claims if c.citation_ids]
            removed += len(view.claims) - len(kept)
            view.claims = kept
        await self._stream_agent(
            AgentId.DIRECTOR,
            system="You are the Research Director. 2 sentences: acknowledge the audit failure and state the fix.",
            user=f"The Auditor struck {removed} uncited claim(s). They are removed; conviction re-scores without them.",
            model=DIRECTOR_MODEL, kind="direction")
        conv = conviction.score(list(s.views.values()), s.objections, s.verdicts, 0)
        s.conviction = conv
        e.conviction_update(conv)

    def _publish(self) -> None:
        super()._publish()
        if self.s.note:
            self.s.note.mode = "live"
